apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pedidos-deployment
  # namespace: postgres
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: postgres-pedidos
  template:
    metadata:
      labels:
        app: postgres-pedidos
    spec:
      containers:
        - name: postgres-pedidos-container
          image: postgres
          envFrom:
            - configMapRef:
                name: db-deployment-pedidos-configmap
            - secretRef:
                name:  postgres-pedidos-secrets
          ports:
            - containerPort: 5432
          


