apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-pedidos-deployment
  # namespace: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-pedidos
  template:
    metadata:
      labels:
        app: challenge-pedidos
    spec:
      # restartPolicy: Always 
      containers:
        - name: challenge-pedidos-container
          image: encortondo/fiap-tech-challenge-pedidos:0.0.1
          ports:
            - containerPort: 8083
          command: ["npm", "run", "start"]
          envFrom:
            - configMapRef:
                name: deployment-pedidos-configmap
            - secretRef:
                name:  challenge-pedidos-secrets

