apiVersion: v1
kind: Service
metadata:
  name: postgres-pedidos-service
  # namespace: postgres
spec:
  selector:
    app: postgres-pedidos
  ports:
    - protocol: TCP
      port: 5432  
      targetPort: 5432
  
