apiVersion: v1
kind: Service
metadata:
  name: challenge-pedidos-service
  # namespace: challenge
spec:
  selector:
    app: challenge-pedidos
  ports:
    - protocol: TCP
      port: 83  # Porta interna do serviço (porta do container)
      targetPort: 8083  # Porta do container
  type: LoadBalancer
